movieproject/movieapp/urls.py
from django.urls import path

from . import views
app_name = 'movieapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movieapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    img = models.ImageField(upload_to='gallery')
    year = models.IntegerField()

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms

from .models import Movie


class Movieform(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import Movieform
from .models import Movie


# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {'movie_list': movie}
    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "detail.html", {'movie': movie})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = Movieform(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html', {'form':form, 'movie':movie})


def delete(request,id):
    if request.method== 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the movie name">
    <br><br>
    <input type="text" name="desc" placeholder="Enter the movie description">
    <br><br>
    <input type="text" name="year" placeholder="Enter the  movie year">
    <br><br>
    <input type="file" name="img">

    <input class="btn btn-success" type="submit" value="Add-to">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Prime CINE HUB
  </a>
</nav>

{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure to delete this movie?
    <br>
    <input type="submit" value="OK">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <img src="{{ movie.img.url }}" width="310" height="320">
        </div>
        <div class="col-md-6">
            <h5>{{movie.name}}</h5>
            <h6>{{movie.desc}}</h6>
            <h6>{{movie.year}}</h6>
            <a class="btn btn-info" href="{% url 'movieapp:update' movie.id %}"> Edit </a>
            <a href="{% url 'movieapp:delete' movie.id %}" class="btn btn-danger"> Delete </a>
        </div>
    </div>
</div>


{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input class="btn btn-success" type="submit" value="Update">

</form>
{% endblock %}

movieproject/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<nav class="navbar navbar-dark bg-dark justify-content-between">
  <a class="navbar-brand" href="#"> Prime CINE HUB</a>
  <form class="form-inline">
    <a href="{% url 'movieapp:add_movie' %}" class="btn btn-outline-success">Upload Movies</a>
  </form>
</nav>

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3 py-1">
            <div class="card">
                <img src="{{ i.img.url }}" class="card-img-top" alt="..." width="100" height="200">
                <div class="card-body">
                    <h6 class="card-title">{{i.name}}</h6>
                    <p class="card-text"></p>
                    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-info">View Details</a>
                </div>
            </div>
        </div>
      {% endfor %}
    </div>
</div>

</body>
</html>